package com.isssr.ticketing_system.service.auto_generated;

import com.isssr.ticketing_system.model.Ticket;
import com.isssr.ticketing_system.model.auto_generated.Query;
import com.isssr.ticketing_system.model.auto_generated.decorator.DataBaseQuery;
import com.isssr.ticketing_system.model.auto_generated.scheduler.TaskScheduler;
import com.isssr.ticketing_system.repository.ProductRepository;
import com.isssr.ticketing_system.repository.TeamRepository;
import com.isssr.ticketing_system.repository.TicketRepository;
import com.isssr.ticketing_system.service.*;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Service;

import java.time.Instant;
import java.util.ArrayList;
import java.util.Observable;
import java.util.Observer;

@Service
public class AutoGeneratedTicketService implements Observer {

    @Autowired
    private ProductRepository productRepository;

    @Autowired
    private TeamRepository teamRepository;

    @Autowired
    private TicketRepository ticketRepository;

    @Autowired
    private TicketService ticketService;

    private ArrayList<Query> activeQuery = new ArrayList<>();

    @Autowired
    private TaskScheduler taskScheduler;

    /** external services **/
    @Autowired
    private TicketStatusService ticketStatusService;

    @Autowired
    private TicketSourceService ticketSourceService;

    @Autowired
    private TicketCategoryService ticketCategoryService;

    @Autowired
    private UserService userService;

    @Autowired
    private ProductService productService;

    @Autowired
    private VisibilityService visibilityService;


    @Override
    public void update(Observable o, Object arg) {

        System.out.println("Query: " + ((Query) o).printQuery() + " --> RUNNING!");

        JpaRepository jpaRepository = null;

        if(o instanceof DataBaseQuery) {

            String repositoryName = ((DataBaseQuery) o).getReferenceClass().getName();

            switch (repositoryName) {
                case "com.isssr.ticketing_system.repository.ProductRepository":

                    jpaRepository = this.productRepository;
                    break;
                case "com.isssr.ticketing_system.repository.TeamRepository":

                    jpaRepository = this.teamRepository;
                    break;
                case "com.isssr.ticketing_system.repository.TicketRepository":

                    jpaRepository = this.ticketRepository;
                    break;
            }

        }

        Boolean result = ((Query) o).executeQuery(jpaRepository);

        if (result != null) {

            if (result) {

                try {

                    generateTicket((Query) o);

                } catch (Exception e) {
                    e.printStackTrace();
                    //TODO generate system error ticket
                    return;
                }
            }

        }


        /*switch (((Query) o).getComparisonOperator()) {
            case EQUALS:

                try {
                    System.out.println("Repository: " + jpaRepository.toString() + "  -->  Elementi presenti: " + ((Query) o).getMethodToCall().invoke(jpaRepository ));
                    if (((Query) o).getMethodToCall().invoke(jpaRepository ) == (Integer) ((Query) o).getReferenceValue())
                        System.out.println("Ticket generated");
                } catch (IllegalAccessException | InvocationTargetException e) {
                    e.printStackTrace();
                }
        }*/

    }

    private void generateTicket(Query query) throws Exception {

        Ticket ticket = new Ticket(
                ticketStatusService.findByName("PENDING").get(),
                ticketSourceService.findByName("SYSTEM").get(),
                Instant.now(),
                ticketCategoryService.findByName("SYSTEM").get(),
                "Auto generated ticket",
                query.printQuery(),
                userService.findByEmail("admin@admin.com").get(),
                productService.findByName("System").get(),
                query.priority(),
                visibilityService.findByName("PRIVATE").get(),
                false
        );

        ticketService.save(ticket);

    }

    public void activateQuery(Query query){
        taskScheduler.addJob(query);
        this.activeQuery.add(query);
        System.out.println("Query: " + query.printQuery() + " --> SCHEDULED");
    }


}
